//! Module defining macros for developing _plugins_.

use super::FnCallArgs;
#[cfg(feature = "no_std")]
use std::prelude::v1::*;

/// Result of a Rhai function.
pub type RhaiResult = crate::RhaiResult;

pub use rhai_codegen::*;

// Removing these re-exports would be a breaking change, despite there are alternate import paths.
// https://github.com/rhaiscript/rhai/issues/1098
pub use super::RhaiFunc;
pub use crate::{
    Dynamic, Engine, EvalAltResult, FnAccess, FnNamespace, FuncRegistration, ImmutableString,
    Module, NativeCallContext, Position,
};
pub use std::{any::TypeId, mem};

/// Trait implemented by a _plugin function_.
///
/// This trait should not be used directly.
pub trait PluginFunc {
    /// Call the plugin function with the arguments provided.
    fn call(&self, context: Option<NativeCallContext>, args: &mut FnCallArgs) -> RhaiResult;

    /// Is this plugin function a method?
    #[must_use]
    fn is_method_call(&self) -> bool;

    /// Does this plugin function contain a [`NativeCallContext`] parameter?
    #[must_use]
    fn has_context(&self) -> bool;

    /// Is this plugin function pure?
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_pure(&self) -> bool {
        true
    }

    /// Is this plugin function volatile?
    ///
    /// A volatile function is not guaranteed to return the same result for the same input(s).
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_volatile(&self) -> bool {
        true
    }
}

/// Static manifest of a _plugin module_, generated by `#[export_module(manifest)]`.
///
/// It lists every exported function without registering any of them. A [`Module`] holding a
/// manifest (see [`Module::from_manifest`] and [`Module::combine_manifest`]) looks up its functions
/// by hash only when they are called.
#[derive(Clone, Copy)]
pub struct ModuleManifest {
    /// Exported functions.
    pub functions: &'static [FnManifestEntry],
    /// Sub-modules.
    pub sub_modules: &'static [(&'static str, &'static ModuleManifest)],
    /// Register everything that is not a function (i.e. constants and custom types) into a [`Module`].
    pub init_eager: fn(&mut Module),
}

/// A function entry in a [`ModuleManifest`].
#[derive(Clone, Copy)]
pub struct FnManifestEntry {
    /// Name of the function, as registered.
    pub name: &'static str,
    /// Function namespace.
    pub namespace: FnNamespace,
    /// The plugin function.
    ///
    /// It is always [`Send`] + [`Sync`] because it lives in a `static`.
    pub func: &'static (dyn PluginFunc + Send + Sync),
    /// Call a function with the parameter types of the plugin function.
    pub param_types: fn(&mut dyn FnMut(&[TypeId])),
    /// Register this function (and only this function), with full metadata, into a [`Module`].
    pub register: fn(&mut Module),
}

// `Debug` cannot be derived for higher-ranked function pointers under the MSRV.
impl std::fmt::Debug for ModuleManifest {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ModuleManifest")
            .field("functions", &self.functions)
            .field("sub_modules", &self.sub_modules)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Debug for FnManifestEntry {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FnManifestEntry")
            .field("name", &self.name)
            .field("namespace", &self.namespace)
            .finish_non_exhaustive()
    }
}

impl ModuleManifest {
    /// Call a function on every exported function, optionally including those in sub-modules
    /// (flattened).
    pub(crate) fn for_each_fn(
        &'static self,
        flatten: bool,
        f: &mut dyn FnMut(&'static FnManifestEntry),
    ) {
        self.functions.iter().for_each(&mut *f);

        if flatten {
            for (.., m) in self.sub_modules {
                m.for_each_fn(flatten, f);
            }
        }
    }
}

impl FnManifestEntry {
    /// Get the number of parameters.
    #[must_use]
    pub(crate) fn num_params(&self) -> usize {
        let mut num_params = 0;
        (self.param_types)(&mut |types| num_params = types.len());
        num_params
    }
    /// Calculate the hash of this function under a namespace path, the same as when it is
    /// registered into (or indexed by) a [`Module`].
    ///
    /// If the function has any [`Dynamic`] parameter, its hash in scripted format (i.e. without
    /// parameter types) is also returned.
    #[must_use]
    pub(crate) fn calc_hash(&self, path: &[&str]) -> (u64, Option<u64>) {
        let is_method = self.func.is_method_call();
        let mut hashes = (0, None);

        (self.param_types)(&mut |types| {
            let hash_script = crate::calc_fn_hash(path.iter().copied(), self.name, types.len());
            let types = types
                .iter()
                .enumerate()
                .map(|(i, &t)| Module::map_type(!is_method || i > 0, t));
            let mut is_dynamic = false;
            let hash = crate::calc_fn_hash_full(
                hash_script,
                types.inspect(|&t| is_dynamic |= t == TypeId::of::<Dynamic>()),
            );
            hashes = (hash, is_dynamic.then_some(hash_script));
        });

        hashes
    }
}
