//! Module defining macros for developing _plugins_.

use super::FnCallArgs;
#[cfg(feature = "no_std")]
use std::prelude::v1::*;

/// Result of a Rhai function.
pub type RhaiResult = crate::RhaiResult;

pub use rhai_codegen::*;

// Removing these re-exports would be a breaking change, despite there are alternate import paths.
// https://github.com/rhaiscript/rhai/issues/1098
pub use super::RhaiFunc;
pub use crate::{
    Dynamic, Engine, EvalAltResult, FnAccess, FnNamespace, FuncRegistration, ImmutableString,
    Module, NativeCallContext, Position,
};
pub use std::{any::TypeId, mem};

pub use super::lazy::{FnLoadRequest, LazyFunctionSource};

/// Trait implemented by a _plugin function_.
///
/// This trait should not be used directly.
pub trait PluginFunc {
    /// Call the plugin function with the arguments provided.
    fn call(&self, context: Option<NativeCallContext>, args: &mut FnCallArgs) -> RhaiResult;

    /// Is this plugin function a method?
    #[must_use]
    fn is_method_call(&self) -> bool;

    /// Does this plugin function contain a [`NativeCallContext`] parameter?
    #[must_use]
    fn has_context(&self) -> bool;

    /// Is this plugin function pure?
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_pure(&self) -> bool {
        true
    }

    /// Is this plugin function volatile?
    ///
    /// A volatile function is not guaranteed to return the same result for the same input(s).
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_volatile(&self) -> bool {
        true
    }
}

/// Static manifest of a _plugin module_, generated by `#[export_module(manifest)]`.
///
/// It lists every exported function without registering any of them, so that functions can be
/// loaded on demand -- one at a time -- when a script calls them.
#[derive(Clone, Copy)]
pub struct ModuleManifest {
    /// Exported functions, sorted by name.
    pub functions: &'static [FnManifestEntry],
    /// Sub-modules, sorted by name.
    pub sub_modules: &'static [(&'static str, &'static ModuleManifest)],
    /// Register everything that is not a function (i.e. constants and custom types) into a [`Module`].
    pub init_eager: fn(&mut Module),
}

/// A function entry in a [`ModuleManifest`].
#[derive(Clone, Copy)]
pub struct FnManifestEntry {
    /// Name of the function, as registered.
    pub name: &'static str,
    /// Number of parameters.
    pub num_params: usize,
    /// Function namespace.
    pub namespace: FnNamespace,
    /// Match argument types against the function's parameter types.
    ///
    /// Returns `None` if they do not match, otherwise the number of [`Dynamic`] parameters used as wildcards.
    pub matches: fn(&[TypeId]) -> Option<usize>,
    /// Register this function (and only this function) into a [`Module`].
    pub register: fn(&mut Module),
}

// `Debug` cannot be derived for higher-ranked function pointers under the MSRV.
impl std::fmt::Debug for ModuleManifest {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ModuleManifest")
            .field("functions", &self.functions)
            .field("sub_modules", &self.sub_modules)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Debug for FnManifestEntry {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FnManifestEntry")
            .field("name", &self.name)
            .field("num_params", &self.num_params)
            .field("namespace", &self.namespace)
            .finish_non_exhaustive()
    }
}

impl ModuleManifest {
    /// Find the best function matching a name and argument types.
    ///
    /// An exact match is preferred over one that needs [`Dynamic`] wildcards.
    #[must_use]
    pub fn find_fn(
        &self,
        name: &str,
        arg_types: &[TypeId],
        global_only: bool,
    ) -> Option<&'static FnManifestEntry> {
        let functions = self.functions;
        let start = functions.partition_point(|f| f.name < name);

        functions[start..]
            .iter()
            .take_while(|f| f.name == name)
            .filter(|f| f.num_params == arg_types.len())
            .filter(|f| !global_only || f.namespace == FnNamespace::Global)
            .filter_map(|f| (f.matches)(arg_types).map(|n| (n, f)))
            .min_by_key(|(n, ..)| *n)
            .map(|(.., f)| f)
    }
    /// Find a sub-module by name.
    #[must_use]
    pub fn find_sub_module(&self, name: &str) -> Option<&'static ModuleManifest> {
        self.sub_modules
            .binary_search_by(|(n, ..)| (*n).cmp(name))
            .ok()
            .map(|i| self.sub_modules[i].1)
    }
}

/// Match argument types against parameter types, treating [`Dynamic`] parameters as wildcards.
///
/// Returns `None` if they do not match, otherwise the number of wildcards used.
#[must_use]
pub fn match_param_types(params: &[TypeId], args: &[TypeId]) -> Option<usize> {
    if params.len() != args.len() {
        return None;
    }

    let dynamic = TypeId::of::<Dynamic>();
    let mut wildcards = 0;

    for (param, arg) in params.iter().zip(args) {
        if param == arg {
            continue;
        }
        if *param != dynamic {
            return None;
        }
        wildcards += 1;
    }

    Some(wildcards)
}
