//! Module defining macros for developing _plugins_.

use super::FnCallArgs;
#[cfg(feature = "no_std")]
use std::prelude::v1::*;

/// Result of a Rhai function.
pub type RhaiResult = crate::RhaiResult;

pub use rhai_codegen::*;

// Removing these re-exports would be a breaking change, despite there are alternate import paths.
// https://github.com/rhaiscript/rhai/issues/1098
pub use super::RhaiFunc;
pub use crate::{
    Dynamic, Engine, EvalAltResult, FnAccess, FnNamespace, FuncRegistration, ImmutableString,
    Module, NativeCallContext, Position,
};
pub use std::{any::TypeId, mem};

/// Trait implemented by a _plugin function_.
///
/// This trait should not be used directly.
pub trait PluginFunc {
    /// Call the plugin function with the arguments provided.
    fn call(&self, context: Option<NativeCallContext>, args: &mut FnCallArgs) -> RhaiResult;

    /// Is this plugin function a method?
    #[must_use]
    fn is_method_call(&self) -> bool;

    /// Does this plugin function contain a [`NativeCallContext`] parameter?
    #[must_use]
    fn has_context(&self) -> bool;

    /// Is this plugin function pure?
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_pure(&self) -> bool {
        true
    }

    /// Is this plugin function volatile?
    ///
    /// A volatile function is not guaranteed to return the same result for the same input(s).
    ///
    /// Defaults to `true` such that any old implementation that has constant-checking code inside
    /// the function itself will continue to work.
    #[inline(always)]
    #[must_use]
    fn is_volatile(&self) -> bool {
        true
    }
}

/// Static manifest of a _plugin module_, generated by `#[export_module(manifest)]`.
///
/// It lists every exported function without registering any of them. A [lazy][Module::set_lazy]
/// [`Module`] holding a manifest resolves functions from it on demand, without allocating.
#[derive(Clone, Copy)]
pub struct ModuleManifest {
    /// Exported functions, sorted by name.
    pub functions: &'static [FnManifestEntry],
    /// Sub-modules, sorted by name.
    pub sub_modules: &'static [(&'static str, &'static ModuleManifest)],
    /// Bloom filter of function names (see [`manifest_name_filter`]), to skip this manifest
    /// quickly when looking up a function that is not in it.
    pub name_filter: [u64; 4],
    /// Register everything that is not a function (i.e. constants and custom types) into a [`Module`].
    pub init_eager: fn(&mut Module),
}

/// A function entry in a [`ModuleManifest`].
#[derive(Clone, Copy)]
pub struct FnManifestEntry {
    /// Name of the function, as registered.
    pub name: &'static str,
    /// Number of parameters.
    pub num_params: usize,
    /// Function namespace.
    pub namespace: FnNamespace,
    /// The plugin function.
    ///
    /// It is always [`Send`] + [`Sync`] because it lives in a `static`.
    pub func: &'static (dyn PluginFunc + Send + Sync),
    /// Do the function's parameter types (as registered) equal the types given by a function
    /// mapping each parameter position to a type?
    pub params_eq: fn(&dyn Fn(usize) -> TypeId) -> bool,
    /// Does the function have any [`Dynamic`] parameter?
    pub has_dynamic: fn() -> bool,
    /// Register this function (and only this function), with full metadata, into a [`Module`].
    pub register: fn(&mut Module),
}

// `Debug` cannot be derived for higher-ranked function pointers under the MSRV.
impl std::fmt::Debug for ModuleManifest {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ModuleManifest")
            .field("functions", &self.functions)
            .field("sub_modules", &self.sub_modules)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Debug for FnManifestEntry {
    #[cold]
    #[inline(never)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FnManifestEntry")
            .field("name", &self.name)
            .field("num_params", &self.num_params)
            .field("namespace", &self.namespace)
            .finish_non_exhaustive()
    }
}

impl ModuleManifest {
    /// Iterate the functions with a particular name.
    #[inline]
    pub fn iter_fn_named<'a>(
        &self,
        name: &'a str,
    ) -> impl Iterator<Item = &'static FnManifestEntry> + 'a {
        let functions = self.functions;
        let start = functions.partition_point(|f| f.name < name);
        functions[start..]
            .iter()
            .take_while(move |f| f.name == name)
    }
    /// Find a function by name and parameter types (given by a function mapping each parameter
    /// position to a type), optionally searching flattened sub-modules.
    ///
    /// `name_hash` is the [`manifest_name_hash`] of `name`.
    ///
    /// This never allocates.
    #[must_use]
    pub fn find_fn(
        &'static self,
        name: &str,
        name_hash: u64,
        num_params: usize,
        param_type: &dyn Fn(usize) -> TypeId,
        flatten: bool,
        global_only: bool,
    ) -> Option<&'static FnManifestEntry> {
        // Sub-modules are flattened after the root, so they take precedence
        if flatten {
            if let Some(f) = self.sub_modules.iter().rev().find_map(|(.., m)| {
                m.find_fn(
                    name,
                    name_hash,
                    num_params,
                    param_type,
                    flatten,
                    global_only,
                )
            }) {
                return Some(f);
            }
        }

        if !self.may_contain_name(name_hash) {
            return None;
        }

        self.iter_fn_named(name)
            .filter(|f| f.num_params == num_params)
            .filter(|f| !global_only || f.namespace == FnNamespace::Global)
            .find(|f| (f.params_eq)(param_type))
    }
    /// Is there any function in the global namespace, optionally searching flattened sub-modules?
    #[must_use]
    pub fn has_global_fn(&self, flatten: bool) -> bool {
        self.functions
            .iter()
            .any(|f| f.namespace == FnNamespace::Global)
            || (flatten
                && self
                    .sub_modules
                    .iter()
                    .any(|(.., m)| m.has_global_fn(flatten)))
    }
    /// Register functions (and only functions) passing a filter into a [`Module`], optionally
    /// flattening sub-modules.
    pub(crate) fn register_filtered(
        &self,
        module: &mut Module,
        flatten: bool,
        filter: impl Fn(FnNamespace, FnAccess, bool, &str, usize) -> bool + Copy,
    ) {
        for f in self.functions {
            if filter(f.namespace, FnAccess::Public, false, f.name, f.num_params) {
                (f.register)(module);
            }
        }
        if flatten {
            for (.., m) in self.sub_modules {
                m.register_filtered(module, flatten, filter);
            }
        }
    }
    /// Can a function with a name (given by its [`manifest_name_hash`]) be in this manifest?
    #[inline(always)]
    #[must_use]
    pub const fn may_contain_name(&self, name_hash: u64) -> bool {
        manifest_name_filter_contains(&self.name_filter, name_hash)
    }
    /// Get the name filter of this manifest, optionally including flattened sub-modules.
    #[must_use]
    pub fn deep_name_filter(&self, flatten: bool) -> [u64; 4] {
        let mut filter = self.name_filter;
        if flatten {
            for (.., m) in self.sub_modules {
                filter
                    .iter_mut()
                    .zip(m.deep_name_filter(flatten))
                    .for_each(|(a, b)| *a |= b);
            }
        }
        filter
    }
    /// Find a sub-module by name.
    #[must_use]
    pub fn find_sub_module(&self, name: &str) -> Option<&'static ModuleManifest> {
        self.sub_modules
            .binary_search_by(|(n, ..)| (*n).cmp(name))
            .ok()
            .map(|i| self.sub_modules[i].1)
    }
}

/// Hash a function name for a [`ModuleManifest`]'s name filter (64-bit FNV-1a).
///
/// This is not seeded, so it can be calculated in `const` context.
#[must_use]
pub const fn manifest_name_hash(name: &str) -> u64 {
    let bytes = name.as_bytes();
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut i = 0;
    while i < bytes.len() {
        hash ^= bytes[i] as u64;
        hash = hash.wrapping_mul(0x0100_0000_01b3);
        i += 1;
    }
    hash
}

/// The two bits (word index and mask) a name hash sets in a name filter.
#[inline(always)]
const fn name_filter_bits(name_hash: u64) -> (usize, u64, usize, u64) {
    let b1 = (name_hash & 0xff) as usize;
    let b2 = ((name_hash >> 8) & 0xff) as usize;
    (b1 / 64, 1 << (b1 % 64), b2 / 64, 1 << (b2 % 64))
}

/// Can a function with a name (given by its [`manifest_name_hash`]) be in a name filter?
#[inline(always)]
#[must_use]
pub const fn manifest_name_filter_contains(filter: &[u64; 4], name_hash: u64) -> bool {
    let (i1, b1, i2, b2) = name_filter_bits(name_hash);
    filter[i1] & b1 != 0 && filter[i2] & b2 != 0
}

/// Build a [`ModuleManifest`]'s name filter (a 256-bit Bloom filter) from function names.
///
/// Used by code generated by `#[export_module(manifest)]`.
#[must_use]
pub const fn manifest_name_filter(names: &[&str]) -> [u64; 4] {
    let mut filter = [0_u64; 4];
    let mut i = 0;
    while i < names.len() {
        let (i1, b1, i2, b2) = name_filter_bits(manifest_name_hash(names[i]));
        filter[i1] |= b1;
        filter[i2] |= b2;
        i += 1;
    }
    filter
}

/// Do the parameter types of a plugin function (as registered into a [`Module`]) equal the types
/// given by a function mapping each parameter position to a type?
///
/// Used by code generated by `#[export_module(manifest)]`.
#[inline]
#[must_use]
pub fn manifest_fn_params_eq(
    param_types: &[TypeId],
    func: &super::native::FnPlugin,
    param_type: &dyn Fn(usize) -> TypeId,
) -> bool {
    let is_method = func.is_method_call();

    param_types
        .iter()
        .enumerate()
        .all(|(i, &t)| Module::map_type(!is_method || i > 0, t) == param_type(i))
}

/// Does a plugin function have any [`Dynamic`] parameter?
///
/// Used by code generated by `#[export_module(manifest)]`.
#[inline]
#[must_use]
pub fn manifest_fn_has_dynamic(param_types: &[TypeId], func: &super::native::FnPlugin) -> bool {
    let is_method = func.is_method_call();

    param_types
        .iter()
        .enumerate()
        .any(|(i, &t)| Module::map_type(!is_method || i > 0, t) == TypeId::of::<Dynamic>())
}
